### ISSUE TITLE
can't build rath docker container

### ISSUE THREAD

**Issue by yepengxj** [Kanaries/Rath#275] opened 2023-01-14 14:49 UTC
Fail to build docker container, please help.

```
Step 11/14 : RUN yarn workspace rath-client build2
 ---> Running in 9e87223a64b9
yarn workspace v1.22.19
yarn run v1.22.19
$ react-app-rewired --max_old_space_size=4096 build
Creating an optimized production build...
Failed to compile.

TypeError: /app/node_modules/@kanaries/loa/build/esm/index.js: Property left of ForOfStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got undefined


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js build2
Directory: /app/packages/rath-client
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
The command '/bin/sh -c yarn workspace rath-client build2' returned a non-zero code: 1
```
Node version: 16/18/latest

**Comment by ObservedObserver** [comment] 2023-01-17 06:45
fixed in https://github.com/Kanaries/Rath/commit/39ee3f832d14e5433786c9462cd9fd60c0b3c7a1

seems to be caused by latest node version.

**Closed by ObservedObserver** 2023-01-17 06:45 UTC
